export const rooms = [
  {
    id: "standard-duplo-casal",
    name: "Standard Duplo",
    description: "Nossos apartamentos são totalmente preparados para descanso e comodidade, todos equipados com ar condicionado individual, telefone com linha direta, cofre, frigobar, internet wi-fi e TV LCD com canais por assinatura.",
    price: "R$ 249,20",
    originalPrice: "R$ 356,00",
    image: "/images/Quartos/Standard Duplo Casal/IMG_0766.jpg",
    capacity: "2 pessoas",
    size: "25m²",
    beds: "1 cama de casal",
    bathrooms: 1,
    hasSuite: false,
    amenities: [
      "Ar Condicionado",
      "Cofre", 
      "Internet Wireless",
      "Mini-Bar",
      "Berço",
      "Chuveiro",
      "TV a Cabo",
      "Café da manhã incluso",
      "Internet wi-fi incluso"
    ],
    rating: 4.5,
    reviews: 89,
    reservationUrl: "https://book.omnibees.com/hotel/1393/room/33108?c=1159&q=1393",
  },
  {
    id: "standard-triplo-casal", 
    name: "Standard Triplo",
    description: "Nossos apartamentos são totalmente preparados para descanso e comodidade, todos equipados com ar condicionado individual, telefone com linha direta, cofre, frigobar, internet wi-fi e TV LCD com canais por assinatura.",
    price: "R$ 311,50",
    originalPrice: "R$ 445,00",
    image: "/images/Quartos/Standard Triplo Casal/IMG_0806.jpg",
    capacity: "3 pessoas",
    size: "30m²", 
    beds: "1 cama de casal + 1 solteiro",
    bathrooms: 1,
    hasSuite: false,
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless", 
      "Mini-Bar",
      "Serviço de Despertar",
      "Chuveiro",
      "TV a Cabo",
      "Café da manhã incluso",
      "Internet wi-fi incluso"
    ],
    rating: 4.6,
    reviews: 112,
    reservationUrl: "https://book.omnibees.com/hotel/1393/room/33109?c=1159&q=1393",
  },
  {
    id: "standard-quadruplo",
    name: "Standard Quádruplo", 
    description: "Nossos apartamentos são totalmente preparados para descanso e comodidade, todos equipados com ar condicionado individual, telefone com linha direta, cofre, frigobar, internet wi-fi e TV LCD com canais por assinatura.",
    price: "R$ 294,40",
    image: "/images/Quartos/Standard Quadruplo/IMG_0790.jpg",
    capacity: "4 pessoas",
    size: "35m²",
    beds: "2 camas de casal",
    bathrooms: 1,
    hasSuite: false,
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless",
      "Banheiro privado",
      "Telefone",
      "Apartamento para não Fumantes",
      "Mini-Bar",
      "TV LCD com canais por assinatura",
      "Café da manhã incluso",
      "Internet wi-fi incluso"
    ],
    rating: 4.7,
    reviews: 156,
    reservationUrl: "https://book.omnibees.com/hotel/1393/room/62316?c=9354&q=1393&NRooms=1&CheckIn=12032026&CheckOut=13032026&ad=1&ch=0&lang=pt-BR&currencyId=16&version=4",
  }
]

export const roomDetails = {
  "standard-duplo-casal": {
    name: "Standard Duplo",
    capacity: 2,
    beds: "1 cama de casal",
    bathrooms: 1,
    hasSuite: false,
    price: "249,20",
    originalPrice: "356,00",
    description: "Nossos apartamentos são totalmente preparados para descanso e comodidade, todos equipados com ar condicionado individual, telefone com linha direta, cofre, frigobar, internet wi-fi e TV LCD com canais por assinatura.",
    images: [
      "/images/Quartos/Standard Duplo Casal/IMG_0766.jpg", 
      "/images/Quartos/Standard Duplo Casal/IMG_0767.jpg",
      "/images/Quartos/Standard Duplo Casal/IMG_0768.jpg",
      "/images/Quartos/Standard Duplo Casal/IMG_0774.jpg",
      "/images/Quartos/Standard Duplo Casal/IMG_0777.jpg"
    ],
    amenities: [
      "Ar Condicionado",
      "Cofre", 
      "Internet Wireless",
      "Mini-Bar",
      "Berço",
      "Chuveiro",
      "TV a Cabo",
      "Café da manhã incluso",
      "Internet wi-fi incluso"
    ],
    reservationUrl: "https://book.omnibees.com/hotel/1393/room/33108?c=1159&q=1393",
  },
  "standard-triplo-casal": {
    name: "Standard Triplo",
    capacity: 3,
    beds: "1 cama de casal + 1 solteiro",
    bathrooms: 1,
    hasSuite: false,
    price: "311,50",
    originalPrice: "445,00",
    description: "Nossos apartamentos são totalmente preparados para descanso e comodidade, todos equipados com ar condicionado individual, telefone com linha direta, cofre, frigobar, internet wi-fi e TV LCD com canais por assinatura.",
    images: [
      "/images/Quartos/Standard Triplo Casal/IMG_0806.jpg",
      "/images/Quartos/Standard Triplo Casal/IMG_0807.jpg", 
      "/images/Quartos/Standard Triplo Casal/IMG_0810.jpg",
      "/images/Quartos/Standard Triplo Casal/IMG_0812.jpg",
      "/images/Quartos/Standard Triplo Casal/IMG_5254.jpg"
    ],
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless",
      "Mini-Bar", 
      "Serviço de Despertar",
      "Chuveiro",
      "TV a Cabo",
      "Café da manhã incluso",
      "Internet wi-fi incluso"
    ],
    reservationUrl: "https://book.omnibees.com/hotel/1393/room/33109?c=1159&q=1393",
  },
  "standard-quadruplo": {
    name: "Standard Quádruplo",
    capacity: 4,
    beds: "2 camas de casal",
    bathrooms: 1,
    hasSuite: false,
    price: "294,40",
    description: "Nossos apartamentos são totalmente preparados para descanso e comodidade, todos equipados com ar condicionado individual, telefone com linha direta, cofre, frigobar, internet wi-fi e TV LCD com canais por assinatura.",
    images: [
      "/images/Quartos/Standard Quadruplo/IMG_0790.jpg",
      "/images/Quartos/Standard Quadruplo/IMG_0792.jpg",
      "/images/Quartos/Standard Quadruplo/IMG_0797.jpg",
      "/images/Quartos/Standard Quadruplo/IMG_0802.jpg",
      "/images/Quartos/Standard Quadruplo/IMG_5252.jpg"
    ],
    amenities: [
      "Ar Condicionado",
      "Cofre",
      "Internet Wireless",
      "Banheiro privado",
      "Telefone",
      "Apartamento para não Fumantes", 
      "Mini-Bar",
      "TV LCD com canais por assinatura",
      "Café da manhã incluso",
      "Internet wi-fi incluso"
    ],
    reservationUrl: "https://book.omnibees.com/hotel/1393/room/62316?c=9354&q=1393&NRooms=1&CheckIn=12032026&CheckOut=13032026&ad=1&ch=0&lang=pt-BR&currencyId=16&version=4",
  }
}
